export const GETLIST_ACTOR_REQUEST = "GETLIST_ACTOR_REQUEST"
export const GETLIST_ACTOR_SUCCESS = "GETLIST_ACTOR_SUCCESS"
export const GETLIST_ACTOR_ERROR = "GETLIST_ACTOR_ERROR"

export const GETBYID_ACTOR_REQUEST = "GETBYID_ACTOR_REQUEST"
export const GETBYID_ACTOR_SUCCESS = "GETBYID_ACTOR_SUCCESS"
export const GETBYID_ACTOR_ERROR = "GETBYID_ACTOR_ERROR"

export const INSERT_ACTOR_REQUEST = "INSERT_ACTOR_REQUEST"
export const INSERT_ACTOR_SUCCESS = "INSERT_ACTOR_SUCCESS"
export const INSERT_ACTOR_ERROR = "INSERT_ACTOR_ERROR"

export const UPDATE_ACTOR_REQUEST = "UPDATE_ACTOR_REQUEST"
export const UPDATE_ACTOR_SUCCESS = "UPDATE_ACTOR_SUCCESS"
export const UPDATE_ACTOR_ERROR = "UPDATE_ACTOR_ERROR"

export const DELETE_ACTOR_REQUEST = "DELETE_ACTOR_REQUEST"
export const DELETE_ACTOR_SUCCESS = "DELETE_ACTOR_SUCCESS"
export const DELETE_ACTOR_ERROR = "DELETE_ACTOR_ERROR"
