export const GETLIST_CUSTOMER_REQUEST = "GETLIST_CUSTOMER_REQUEST"
export const GETLIST_CUSTOMER_SUCCESS = "GETLIST_CUSTOMER_SUCCESS"
export const GETLIST_CUSTOMER_ERROR = "GETLIST_CUSTOMER_ERROR"

export const GETBYID_CUSTOMER_REQUEST = "GETBYID_CUSTOMER_REQUEST"
export const GETBYID_CUSTOMER_SUCCESS = "GETBYID_CUSTOMER_SUCCESS"
export const GETBYID_CUSTOMER_ERROR = "GETBYID_CUSTOMER_ERROR"

export const INSERT_CUSTOMER_REQUEST = "INSERT_CUSTOMER_REQUEST"
export const INSERT_CUSTOMER_SUCCESS = "INSERT_CUSTOMER_SUCCESS"
export const INSERT_CUSTOMER_ERROR = "INSERT_CUSTOMER_ERROR"

export const DELETE_CUSTOMER_REQUEST = "DELETE_CUSTOMER_REQUEST"
export const DELETE_CUSTOMER_SUCCESS = "DELETE_CUSTOMER_SUCCESS"
export const DELETE_CUSTOMER_ERROR = "DELETE_CUSTOMER_ERROR"
